---
title: Analysis
description:
toc: true
featuredVideo:
featuredImage: https://s.marketwatch.com/public/resources/images/MW-BV988_sat_te_MG_20140305143435.jpg
draft: false
---


<div id="TOC">

</div>

<p>We describe here our detailed data analysis.</p>
<hr />
<div id="data-description" class="section level2">
<h2>Data Description:</h2>
<p>The variables we are most interested in are total math and verbal SAT scores as well as family income — namely, we want to examine whether or not there exists a statistically significant relationship between family income and SAT scores, and the form of these relationships (i.e., linear, logistic, etc.). Over the past several years, more and more questions have arose regarding whether or not colleges (and the rest of the world) should be looking at SAT scores as a credible measure of aptitude and intelligence, or if they are simply another tool for the privileged to remain at the top.</p>
</div>
<div id="important-questions" class="section level2">
<h2>Important Questions:</h2>
<p>As a reminder, some questions we would like to answer in our analysis are:</p>
<ol style="list-style-type: decimal">
<li>What is the nature of the relationship between family income and SAT scores?</li>
<li>Is this relationship statistically significant?</li>
<li>Are there differences in income and SAT scores between states?</li>
<li>Is GPA more affected by family income than SAT scores?</li>
<li>Are other factors, like gender and year, better predictors of SAT scores?</li>
<li>Do any of these relationships change over time?</li>
</ol>
<div id="figure-1-six-states-comparison" class="section level3">
<h3>Figure 1: Six States Comparison</h3>
<p>We began our exploratory data analysis by examining the average SAT score across six different states: the three states with the highest median household incomes, and the three states with the lowest median household incomes.</p>
<p><img src="/analysis_files/figure-html/figure%201-1.png" width="672" /></p>
<p>We can see that this plot does not support our conjecture that higher family incomes lead to higher SAT scores, as the scores for Arkansas and Mississippi, two of the states with the lowest median household income in the country, have higher average SAT scores than all three states with the highest median household incomes. We then wanted to see if any states in particular had higher SAT scores, so we decided to create some figures that examine all 50 states as well as D.C., Puerto Rico, and the Virgin Islands.</p>
</div>
<div id="figure-2-all-states-and-their-average-sat-scores" class="section level3">
<h3>Figure 2: All States and their Average SAT Scores</h3>
<p>To further see if there are significant differences in SAT scores across states, we decided to make a plot with boxplots of all states.</p>
<p><img src="/analysis_files/figure-html/figure%202-1.png" width="672" />
Here we can see that across all U.S. territories, there are notable differences in median SAT scores. This plot shows Iowa with the highest median SAT score, which could be explained by the fact that the Midwest dominates the SAT according to a Forbes article. The region with the lowest SAT median SAT score is the Virgin Islands, followed by Puerto Rico, the only other U.S. Territory not considered a state. This will be further discussed in our next figure, as we opted to look at the SAT scores across different regions of the continental U.S.</p>
</div>
<div id="figure-3-breakdown-of-average-sat-scores-by-region" class="section level3">
<h3>Figure 3: Breakdown of Average SAT Scores by Region</h3>
<p><img src="/analysis_files/figure-html/figure%203-1.png" width="672" /></p>
<p>From both figures we see that the Midwest indisputably has the highest SAT scores overall with most of the states in the region’s data showing scores exceeding 1175 while the other regions had SAT scores lower than 1175. This seemed odd to us, so we did a bit of research and found that it has been a repeating pattern for students in the Midwest to dominate the exam. As it turns out, from a <a href="https://www.forbes.com/sites/bentaylor/2014/07/17/why-the-midwest-dominates-the-sat/?sh=15c87cf72f37">Forbes article</a>, we learned that most students in the Midwest opt to not take any standardized college entrance exams, and if they do, most choose to only take the ACT. Thus, the majority of the students taking the SAT in the Midwest are the very “best” students; that is, students who want to attend the most prestigious colleges, most of whose applications require an SAT score, so the overall scores are higher.</p>
<p>Additionally, the noncontiguous U.S. territories have the lowest scores, with all of the data for SAT scores falling below 850 in the Virgin Islands and below 950 in Puerto Rico. We hypothesized that household income may impact SAT scores, so we looked into the median hosuehold income in these regions with the lowest SAT scores. According to the <a href="https://www.justice.gov/ust/eo/bapcpa/20101101/bci_data/median_income_table.htm">Department of Justice</a>, both of these territories had significantly lower median household incomes in 2010. To further explore this pattern we noticed, we decided to look into relationships between income bracket and average SAT scores.</p>
</div>
<div id="figure-4-income-bracket-and-average-sat-scores" class="section level3">
<h3>Figure 4: Income Bracket and Average SAT Scores</h3>
<p>Our fourth figure shows the average SAT score across the six income brackets in our dataset.</p>
<p><img src="/analysis_files/figure-html/figure%204-1.png" width="672" /></p>
<p>Figure 4 examines the relationship between income bracket and average SAT score. Clearly, we see a steady rise in SAT score as the income bracket increases, with the average SAT score for students with household income of 20k or less is about 920 while the average SAT score for students with household income of 100k and over is about 1126. This supports our hypothesis that income is the best predictor of SAT score. Interestingly, the biggest gap in SAT scores seems to be in between the brackets “income under 20k”, which has an average SAT score of 920, and “income between 20 and 40k”, which has an average SAT score of 1002. This indicates that those in the lowest income bracket faces the most difficulty in doing well on the exam, which makes sense, as there have been many studies showing that the stress of living in poverty negatively affects how one’s brain functions.</p>
</div>
<div id="figure-4-inference" class="section level3">
<h3>Figure 4 Inference:</h3>
<p>To get an idea of how strong the relationship between income bracket and average SAT score is, we decided to summarize a linear model of the figure 4.</p>
<pre><code>## 
## Call:
## lm(formula = incomescore ~ income, data = lm2)
## 
## Residuals:
##     1     2     3     4     5 
## -31.0  24.2  25.4   0.6 -19.2 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 9.182e+02  3.064e+01  29.965 8.16e-05 ***
## income      2.440e-03  4.620e-04   5.282   0.0132 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 29.22 on 3 degrees of freedom
## Multiple R-squared:  0.9029, Adjusted R-squared:  0.8705 
## F-statistic:  27.9 on 1 and 3 DF,  p-value: 0.01323</code></pre>
<p>We see here that there is a very strong positive correlation between income bracket and SAT score, as the R^2 value is very high at 0.8705 and the absolute value of the t-stat for income is greater than 2.</p>
<p>Now that we have evidence suggesting that income bracket is a good predictor for SAT score, we decided to look at some other potential predictors.</p>
</div>
<div id="figure-5-sat-scores-by-gender-2005-2015" class="section level3">
<h3>Figure 5: SAT Scores by Gender, 2005-2015</h3>
<p>To look at whether or not there is a significant difference in SAT scores between genders, we took the yearly average SAT scores of males and females and plotted them.</p>
<p><img src="/analysis_files/figure-html/figure%205-1.png" width="672" /></p>
<p>We can see here that throughout all 10 years of data in the dataset, there is a notable difference between genders for average SAT score. All of the data for average SAT score of females are below 1060 while all the data for males falls between 1080 and 1100. In order to look at this in more detail, we decided to create plots for the two sections of the SAT.</p>
<p><img src="/analysis_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p><img src="/analysis_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>As we can clearly see in these plots, there is a much bigger difference between genders for the math section of the SAT compared to the verbal, and that the differences sometime differ in different years. For math SAT scores, there was at least a 25 point difference but for the verbal section there was at most about a 10 point difference.</p>
<p>We wondered why this was the case and found a <a href="https://www.forbes.com/sites/kimelsesser/2016/07/01/is-the-college-board-making-the-sat-more-difficult-for-women/?sh=19d2eb3a5f35">Forbes article</a> that explains a possible reason behind the gender difference in SAT scores: stereotype threat. Certain questions on the SAT, such as one asking test-takers to look at a graph showing more boys than girls in math classes, can wreak psychological havoc on female students’ minds during the exam, in turn worsening their performance. Until CollegeBoard takes significant action to overhaul the gender bias within their exams, it is possible that gender will be a good predictor of SAT scores.</p>
<pre><code>## 
## Call:
## lm(formula = average.SAT.score ~ gdummy, data = genderdummies)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -285.80  -66.80  -19.28   75.24  180.21 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 1088.795      3.758 289.724  &lt; 2e-16 ***
## gdummy       -42.031      5.315  -7.909 6.07e-15 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 90.27 on 1152 degrees of freedom
## Multiple R-squared:  0.0515, Adjusted R-squared:  0.05067 
## F-statistic: 62.54 on 1 and 1152 DF,  p-value: 6.068e-15</code></pre>
<p>Summarizing the linear regression model for gender and SAT score required a slightly different process than income bracket, since gender is a categorical variable. To account for this, we created a dummy variable “female,” where “1” represents female and “0” represents male, then ran a linear regression on this variable and SAT score. We found that the gender dummy variable has a t-stat of -7.9, indicating that there is a statistically significant relationship between gender and SAT score.</p>
</div>
<div id="figure-6-average-sat-score-by-year" class="section level3">
<h3>Figure 6: Average SAT Score by Year</h3>
<p><img src="/analysis_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Across all 10 years in the dataset, the overall average SAT score remained within a 20-point range, which indicates that time itself is not the best predictor for SAT score.</p>
</div>
<div id="backwards-selection-model" class="section level3">
<h3>Backwards Selection Model</h3>
<p>To consolidate all of our figures above, we created a model using backwards selection to find the most significant predictors of SAT score.</p>
<pre><code>##   (Intercept) income.between.20.40k income.between.40.60k income.between.60.80k
## 1        TRUE                 FALSE                 FALSE                 FALSE
## 2        TRUE                 FALSE                 FALSE                 FALSE
## 3        TRUE                 FALSE                 FALSE                 FALSE
## 4        TRUE                 FALSE                 FALSE                 FALSE
## 5        TRUE                  TRUE                 FALSE                 FALSE
## 6        TRUE                  TRUE                  TRUE                 FALSE
## 7        TRUE                  TRUE                  TRUE                  TRUE
## 8        TRUE                  TRUE                  TRUE                  TRUE
##   income.between.80.100k income.less.than.20k income.more.than.100k
## 1                  FALSE                FALSE                 FALSE
## 2                  FALSE                FALSE                 FALSE
## 3                  FALSE                FALSE                 FALSE
## 4                   TRUE                FALSE                 FALSE
## 5                   TRUE                FALSE                 FALSE
## 6                   TRUE                FALSE                 FALSE
## 7                   TRUE                FALSE                 FALSE
## 8                   TRUE                 TRUE                 FALSE
##   female.total.score male.total.score  year
## 1              FALSE             TRUE FALSE
## 2               TRUE             TRUE FALSE
## 3               TRUE             TRUE  TRUE
## 4               TRUE             TRUE  TRUE
## 5               TRUE             TRUE  TRUE
## 6               TRUE             TRUE  TRUE
## 7               TRUE             TRUE  TRUE
## 8               TRUE             TRUE  TRUE</code></pre>
<pre><code>## [1] 20047.563612    36.057809    15.379587     6.175273     4.260576
## [6]     5.308721     6.099692     8.030843</code></pre>
<p>Out of the 8 models produced, model 5 has the lowest Mallow’s CP value at 4.260576 and thus would be the best model. In this one, the predictor variables are:</p>
<ul>
<li>income between 20-40k</li>
<li>income between 80-100k</li>
<li>female total score</li>
<li>male total score</li>
<li>year</li>
</ul>
<p>Thus, income and gender are the best predictors for SAT score according to our dataset.</p>
</div>
</div>
